# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fullcourt Development
email: zourtney@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developer by day...coder by night! This is the personal website of Courtney
  Christensen. Come on in.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fullcourtdev.com" # the base hostname & protocol for your site
github_username: zourtney
linkedin_url: "http://www.linkedin.com/pub/courtney-christensen/1b/63/ba0/"
twitter_username: zourtney
stackoverflow_username: zourtney

# Build settings
markdown: kramdown
